### ISSUE TITLE
Add Hook to unset up to date state if default language content is changed

### ISSUE THREAD

**Issue by mxub** [flokosiol/kirby-translations#5]
What I would love to see would be something like this:

My website is mainly in german. So if there are updates they would be in `file.de.txt`. But that means, if I update the German file the English file is not longer up to date. (Also `file.de.txt` is always up to date)

So I guess it would be nice to have a hook that sets the non-default languages on not-up-to-date on change of the default-language

**Comment by flokosiol** [comment]
Thanks for your suggestion. 

I like that idea, but what if you just fix a typo in your default language and than all your other languages are marked as not up to date anymore?

I think there should be at least some kind of control for the editor. But the only possible solution I can image (at the moment) is another checkbox or link "mark all other languages as not up to date". 

Any other ideas? 

I'm not sure if I like it, because it adds more complexity and I like to keep things as simple as possible. But if your website is translated to a lot of different languages it may save you some time. 

What do you think? I would love to get some feedback :)

**Comment by mxub** [comment]
I can only speak for me but I am already annoyed with only two languages and setting the English one to not translated

----

I for one would flip the default:

If I add content to the default language all other languages are marked as not up to date
and maybe there could be a two click button (not to easy to click) to set all languages back to up to date ?

**Comment by flokosiol** [comment]
Thanks for the quick reply. 

I think the two possible defaults "keep translation status for all other languages" vs. "mark all other languages as not up to date" when changing content for the default language could be an option in config.php – so no problems here. 

We could start with this and see if there's a need for more control for the editor … and if, how to implement this seamlessly.

**Comment by flokosiol** [comment]
I decided to not add this feature to the plugin (at least for now), but you can use [this gist](https://gist.github.com/flokosiol/2b62f891ebe5047782230708c3207aba) to add the functionality yourself. Just copy the lines to your `config.php` or a custom plugin file and change [this fieldname](https://gist.github.com/flokosiol/2b62f891ebe5047782230708c3207aba#file-translations-php-L14) to match the key of your translation field.
